server:
  port: 8082

spring:
  application:
    name: cards-service
  datasource:
    url: jdbc:h2:mem:bankdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true   # ← AJOUTE CETTE LIGNE
 
logging:
  level:
    com.cards: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"